pipeline{

	agent any

	tools {
	    gradle 
	}

	environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub_canv2110')
		//COMMIT_HASH = sh(returnStdout: true, script: 'git rev-parse --short=4 HEAD').trim()
        //BRANCH = "${env.GIT_BRANCH}"
        //TAG = "${env.BRANCH}.${env.BUILD_NUMBER}".drop(15)
        //DEV_TAG = "${env.BRANCH}.${env.BUILD_NUMBER}".drop(7)
        //#VERSION = "${env.TAG}"
	}

	stages {

        stage('Docker build image') {
			steps {
				sh 'docker build -t canv2110/nodeapp_app:$BUILD_TIMESTAMP .'
			}
		}

		stage('Docker Hub Login') {
			steps {
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW'
				//sh 'echo $BRANCH'   sh 'echo $TAG' sh 'echo $DEV_TAG'
				sh 'docker login -u $DOCKERHUB_CREDENTIALS_USR -p $DOCKERHUB_CREDENTIALS_PSW'
			}
		}

		stage('Docker image push') {
			steps {
				sh 'docker push canv2110/nodeapp_app:$BUILD_TIMESTAMP'
			}
		}
	}

	post {
		always {
			sh 'docker logout'
		}
	}

}
